### ISSUE TITLE
Core team members should never get coins for PRs regardless of CODEOWNERS

### ISSUE THREAD

**Issue by gwynne** [vapor/penny-bot#89]
There are a few cases here and there where the `CODEOWNERS` files list only Tim or only me as owner, for various reasons, as well as the case of PostgresNIO where there is deliberately no `CODEOWNERS` at all. Penny should nonetheless refrain from granting anyone on the Core team coins for PRs. In this context, "on the Core team" can be defined as either:

- Membership in the @vapor/core GitHub team, or
- Having the `@core` role on Discord

Either definition works; whichever is easier to implement is fine. If _both_ options are excessively painful, have it filter according to the `CODEOWNERS` of the [vapor/.github](https://github.com/vapor/.github) repo (which I will create if needed), which we'll arbitrarily define as always representing the core team membership.

**Comment by MahdiBM** [comment]
fixed in 3f4a4dd46175dc09fe6edb04150136678bbbc617

**Comment by gwynne** [comment]
Not fixed. You just hardcoded the names, that's not a real fix.
